import {test} from 'node:test';
import assert from 'node:assert/strict';
import worker,{hashPassword} from './dist/server/index.js';
import {localDatabase} from './local-db.mjs';
import {readFileSync} from 'node:fs';
test('Fresh production deployment starts with only its administrator and no demo products',async()=>{
 const DB=localDatabase(),env={DB,SEED_DEMO_PRODUCTS:'0',ADMIN_PASSWORD_HASH:await hashPassword('FreshAdmin123')};
 assert.equal((await worker.fetch(new Request('https://test.example/'),env)).status,200);
 assert.equal(DB.raw.prepare('SELECT COUNT(*) AS n FROM users').get().n,1);
 assert.equal(DB.raw.prepare('SELECT COUNT(*) AS n FROM products').get().n,0);
 assert.equal(DB.raw.prepare('SELECT COUNT(*) AS n FROM orders').get().n,0);
 assert.equal((await worker.fetch(new Request('https://test.example/'),env)).status,200);
 assert.equal(DB.raw.prepare('SELECT COUNT(*) AS n FROM products').get().n,0);DB.raw.close();
});
test('Six-character passwords work for registration, login and password changes',async()=>{
 const DB=localDatabase(),env={DB,ADMIN_PASSWORD_HASH:await hashPassword('OriginalPassword123')};
 const post=(path,data,cookie='')=>worker.fetch(new Request('https://test.example'+path,{method:'POST',headers:{cookie,origin:'https://test.example'},body:new URLSearchParams(data)}),env);
 for(const path of ['/login','/register']){const text=await(await worker.fetch(new Request('https://test.example'+path),env)).text();assert.match(text,/minlength="6"/);assert.doesNotMatch(text,/本站账号与QQ密码无关|密码至少10位/);}
 await post('/register',{username:'sixuser',password:'abc123'});assert.ok(DB.raw.prepare("SELECT id FROM users WHERE username='sixuser'").get());
 assert.ok((await post('/login',{username:'sixuser',password:'abc123'})).headers.get('set-cookie'));
 await post('/register',{username:'shortuser',password:'abc12'});assert.equal(DB.raw.prepare("SELECT id FROM users WHERE username='shortuser'").get(),undefined);
 const r=await post('/login',{username:'admin',password:'OriginalPassword123'}),cookie=r.headers.get('set-cookie').split(';')[0],csrf=DB.raw.prepare('SELECT csrf FROM sessions WHERE user_id=1').get().csrf;
 await post('/admin/password',{csrf,current:'OriginalPassword123',password:'abc12'},cookie);assert.ok(DB.raw.prepare('SELECT csrf FROM sessions WHERE user_id=1').get());
 await post('/admin/password',{csrf,current:'OriginalPassword123',password:'abc123'},cookie);assert.ok((await post('/login',{username:'admin',password:'abc123'})).headers.get('set-cookie'));
 DB.raw.close();
});
test('Admin image uploads persist and display; invalid files and unauthorized writes are rejected',async()=>{
 const objects=new Map(),DB=localDatabase();
 const env={DB,ADMIN_PASSWORD_HASH:await hashPassword('SecureTestPassword123'),BUCKET:{put:async(k,b,o)=>objects.set(k,{bytes:new Uint8Array(b),options:o}),get:async k=>objects.has(k)?{body:objects.get(k).bytes}:null}};
 const post=(path,body,cookie='')=>worker.fetch(new Request('https://test.example'+path,{method:'POST',headers:{cookie,origin:'https://test.example'},body}),env);
 const login=await post('/login',new URLSearchParams({username:'admin',password:'SecureTestPassword123'}));const cookie=login.headers.get('set-cookie').split(';')[0],csrf=DB.raw.prepare('SELECT csrf FROM sessions WHERE user_id=1').get().csrf;
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6zEIAAAAASUVORK5CYII=','base64');
 const data=(bytes,type='image/png',fields={})=>{const f=new FormData();for(const [k,v] of Object.entries({csrf,title:'图片奖励',description:'保留说明',cost:'2000',stock:'5',emoji:'🎁',...fields}))f.set(k,v);f.set('image',new Blob([bytes],{type}),'reward.'+(type==='image/jpeg'?'jpg':'png'));return f;};
 let r=await post('/admin/product',data(png),cookie);assert.equal(r.status,303);assert.equal(objects.size,1);
 const product=DB.raw.prepare("SELECT * FROM products WHERE title='图片奖励'").get();assert.match(product.image_key,/\.png$/);
 r=await worker.fetch(new Request('https://test.example/product-images/'+product.image_key),env);assert.equal(r.headers.get('content-type'),'image/png');assert.deepEqual(Buffer.from(await r.arrayBuffer()),png);
 const home=await worker.fetch(new Request('https://test.example/'),env);assert.match(await home.text(),new RegExp('/product-images/'+product.image_key));
 const jpeg=readFileSync('assets/mountain.jpg');r=await post('/admin/product-image',data(jpeg,'image/jpeg',{id:String(product.id)}),cookie);assert.equal(r.status,303);
 const updated=DB.raw.prepare('SELECT image_key FROM products WHERE id=?').get(product.id).image_key;assert.match(updated,/\.jpg$/);assert.notEqual(updated,product.image_key);
 r=await worker.fetch(new Request('https://test.example/product-images/'+updated),env);assert.equal(r.headers.get('content-type'),'image/jpeg');assert.equal((await r.arrayBuffer()).byteLength,jpeg.length);
 const count=objects.size;
 assert.equal((await post('/admin/product',data(png),'')).status,403);
 assert.equal((await post('/admin/product',data(png,'image/png',{csrf:'bad'}),cookie)).status,403);
 r=await post('/admin/product',data('<svg onload="alert(1)"></svg>'),cookie);assert.equal(r.status,400);assert.match(await r.text(),/保留说明/);
 r=await post('/admin/product',data(new Uint8Array(2*1024*1024+1)),cookie);assert.equal(r.status,400);assert.equal(objects.size,count);
 const missing=new FormData();missing.set('csrf',csrf);missing.set('id',String(product.id));assert.equal((await post('/admin/product-image',missing,cookie)).status,400);
 assert.equal(DB.raw.prepare('SELECT image_key FROM products WHERE id=?').get(product.id).image_key,updated);
 assert.equal((await worker.fetch(new Request('https://test.example/product-images/'+product.image_key),env)).status,404);
 assert.equal((await worker.fetch(new Request('https://test.example/product-images/invalid.svg'),env)).status,404);
 env.BUCKET.put=async()=>{throw Error('Storage unavailable');};r=await post('/admin/product',data(png),cookie);assert.equal(r.status,503);assert.match(await r.text(),/保留说明/);
 assert.equal(DB.raw.prepare("SELECT COUNT(*) AS n FROM products WHERE title='图片奖励'").get().n,1);
 DB.raw.close();
});
test('Game snapshots subtract historical spend, survive repeat imports and account for refunds',async()=>{
 const DB=localDatabase(),env={DB,ADMIN_PASSWORD_HASH:await hashPassword('SecureTestPassword123')};
 const post=(path,data,cookie='')=>worker.fetch(new Request('https://test.example'+path,{method:'POST',headers:{cookie,origin:'https://test.example','content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams(data)}),env);
 let r=await post('/login',{username:'admin',password:'SecureTestPassword123'});const admin=r.headers.get('set-cookie').split(';')[0],csrf=DB.raw.prepare('SELECT csrf FROM sessions WHERE user_id=1').get().csrf;
 await post('/register',{username:'snapshotplayer',password:'PlayerPassword123'});
 const uid=DB.raw.prepare("SELECT id FROM users WHERE username='snapshotplayer'").get().id;
 DB.raw.prepare("UPDATE users SET verified=1,character_name='测试角色' WHERE id=?").run(uid);
 r=await post('/login',{username:'snapshotplayer',password:'PlayerPassword123'});const player=r.headers.get('set-cookie').split(';')[0],pc=DB.raw.prepare('SELECT csrf FROM sessions WHERE user_id=?').get(uid).csrf;
 const state=()=>DB.raw.prepare('SELECT balance,game_total FROM users WHERE id=?').get(uid);
 const sync=total=>post('/admin/sync-points',{csrf,user_id:uid,game_total:total,reason:'游戏截图'},admin);
 // A legacy account has no recorded game snapshot but has existing orders.
 await post('/admin/points',{csrf,user_id:uid,delta:13000,reason:'升级前已有帮贡'},admin);
 await post('/redeem',{csrf:pc,id:4},player);assert.equal(state().balance,11000);assert.equal(state().game_total,null);
 await sync(13000);assert.equal(state().balance,11000);
 await sync(18000);assert.equal(state().balance,16000);assert.equal(state().game_total,18000);
 await sync(18000);await sync(18000);assert.equal(state().balance,16000);
 assert.equal(DB.raw.prepare('SELECT delta FROM ledger ORDER BY id DESC LIMIT 1').get().delta,0);
 const home=await worker.fetch(new Request('https://test.example/',{headers:{cookie:player}}),env);const text=await home.text();assert.match(text,/18,000/);assert.match(text,/2,000/);assert.match(text,/16,000/);
 await post('/admin/order',{csrf,id:1,status:'fulfilled'},admin);await sync(18000);assert.equal(state().balance,16000);
 await post('/redeem',{csrf:pc,id:4},player);await sync(18000);assert.equal(state().balance,14000);
 await post('/admin/order',{csrf,id:2,status:'refunded'},admin);assert.equal(state().balance,16000);
 await sync(18000);assert.equal(state().balance,16000);
 await post('/admin/order',{csrf,id:2,status:'refunded'},admin);assert.equal(state().balance,16000);
 // Low/invalid totals and unauthorized requests cannot change the account.
 await sync(1000);assert.equal(state().balance,16000);assert.equal(state().game_total,18000);
 for(const total of ['',-1,'1.5','NaN','1000000001'])await sync(total);
 assert.equal(state().balance,16000);
 assert.equal((await post('/admin/sync-points',{csrf:pc,user_id:uid,game_total:999999},player)).status,403);
 assert.equal((await post('/admin/sync-points',{csrf:'bad',user_id:uid,game_total:999999},admin)).status,403);
 // A valid corrected total can decrease, without erasing redeemed points.
 await sync(17000);assert.equal(state().balance,15000);
 await sync(2000);assert.equal(state().balance,0);
 await sync(18000);await post('/redeem',{csrf:pc,id:4},player);await sync(19000);assert.equal(state().balance,15000);
 const sum=DB.raw.prepare('SELECT SUM(delta) AS n FROM ledger WHERE user_id=?').get(uid).n;assert.equal(sum,state().balance);
 assert.equal(DB.raw.prepare('SELECT COUNT(*) AS n FROM orders').get().n,3);
 DB.raw.close();
});
test('Full account, binding, ledger, redemption and refund workflow',async()=>{
 const DB=localDatabase(),env={DB,ADMIN_PASSWORD_HASH:await hashPassword('SecureTestPassword123')};
 const get=(path,cookie='')=>worker.fetch(new Request('https://test.example'+path,{headers:{cookie}}),env);
 const post=(path,data,cookie='')=>worker.fetch(new Request('https://test.example'+path,{method:'POST',headers:{cookie,origin:'https://test.example','content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams(data)}),env);
 assert.equal((await get('/')).status,200);assert.equal(DB.raw.prepare('SELECT COUNT(*) AS n FROM products').get().n,4);
 let r=await post('/login',{username:'admin',password:'SecureTestPassword123'});const admin=r.headers.get('set-cookie').split(';')[0];
 assert.ok(admin);const as=DB.raw.prepare('SELECT csrf FROM sessions WHERE user_id=1').get().csrf;
 assert.equal((await get('/admin',admin)).status,200);
 r=await post('/register',{username:'player',password:'PlayerPassword123'});assert.match(r.headers.get('location'),/login/);
 r=await post('/login',{username:'player',password:'PlayerPassword123'});const player=r.headers.get('set-cookie').split(';')[0],uid=DB.raw.prepare("SELECT id FROM users WHERE username='player'").get().id,ps=DB.raw.prepare('SELECT csrf FROM sessions WHERE user_id=?').get(uid).csrf;
 assert.equal((await get('/admin',player)).status,403);
 assert.equal((await post('/admin/points',{csrf:ps,user_id:uid,delta:1000,reason:'attack'},player)).status,403);
 assert.equal((await post('/admin/points',{csrf:'wrong',user_id:uid,delta:1000,reason:'test'},admin)).status,403);
 r=await post('/admin/code',{csrf:as,qq:'123456789',character:'测试角色'},admin);const code=(await r.text()).match(/class="big gold">([A-F0-9]{10})</)[1];
 r=await post('/bind',{csrf:ps,qq:'123456789',code},player);assert.equal(DB.raw.prepare('SELECT verified FROM users WHERE id=?').get(uid).verified,1);
 assert.ok(DB.raw.prepare('SELECT used_at FROM bind_codes LIMIT 1').get().used_at);
 await post('/admin/points',{csrf:as,user_id:uid,delta:800,reason:'活动奖励'},admin);
 await post('/redeem',{csrf:ps,id:1},player);assert.equal(DB.raw.prepare('SELECT balance FROM users WHERE id=?').get(uid).balance,300);assert.equal(DB.raw.prepare('SELECT stock FROM products WHERE id=1').get().stock,9);
 await post('/redeem',{csrf:ps,id:1},player);assert.equal(DB.raw.prepare('SELECT COUNT(*) AS n FROM orders').get().n,1);
 await post('/admin/order',{csrf:as,id:1,status:'refunded'},admin);await post('/admin/order',{csrf:as,id:1,status:'refunded'},admin);
 assert.equal(DB.raw.prepare('SELECT balance FROM users WHERE id=?').get(uid).balance,800);assert.equal(DB.raw.prepare('SELECT stock FROM products WHERE id=1').get().stock,10);
 assert.equal(DB.raw.prepare('SELECT COUNT(*) AS n FROM ledger').get().n,3);
 await post('/admin/points',{csrf:as,user_id:uid,delta:-900,reason:'invalid'},admin);assert.equal(DB.raw.prepare('SELECT balance FROM users WHERE id=?').get(uid).balance,800);
 await post('/redeem',{csrf:ps,id:1},player);await post('/admin/order',{csrf:as,id:2,status:'fulfilled'},admin);await post('/admin/order',{csrf:as,id:2,status:'refunded'},admin);assert.equal(DB.raw.prepare('SELECT balance FROM users WHERE id=?').get(uid).balance,300);
 assert.match(await (await get('/records',player)).text(),/已发放/);
 await post('/admin/password',{csrf:as,current:'SecureTestPassword123',password:'ChangedPassword123'},admin);assert.equal((await get('/admin',admin)).status,303);
 assert.ok((await post('/login',{username:'admin',password:'ChangedPassword123'})).headers.get('set-cookie'));
 DB.raw.close();
});
